### ISSUE TITLE
[4.1.0 Migration] Error while migrating API Manager components

### ISSUE THREAD

**Issue by binodmx** [wso2-extensions/apim-migration-resources#283]
**Description:**
Getting following error while migrating APIM 2.6.0 to APIM 4.1.0 in [Step 4: Migrate the API Manager Components](https://apim.docs.wso2.com/en/latest/install-and-setup/upgrading-wso2-api-manager/260-to-410/upgrading-from-260-to-410/#step-4-migrate-the-api-manager-components).

```
[2022-09-26 15:19:14,211] ERROR - Framework FrameworkEvent ERROR
java.lang.NullPointerException: null
    at org.wso2.carbon.apimgt.migration.dao.APIMgtDAO.updateUUIDAndStatus(APIMgtDAO.java:756) ~[org.wso2.carbon.apimgt.migrate.client-4.1.0.36.jar:?]
    at org.wso2.carbon.apimgt.migration.migrator.v400.V400DBDataMigrator.moveUUIDToDBFromRegistry(V400DBDataMigrator.java:260) ~[org.wso2.carbon.apimgt.migrate.client-4.1.0.36.jar:?]
    at org.wso2.carbon.apimgt.migration.migrator.v400.V400DBDataMigrator.migrate(V400DBDataMigrator.java:95)
...
```

When we debugged the code we found that `apiInfoDTO` has `null` value for `status` property. It's because in [here](https://github.com/wso2-extensions/apim-migration-resources/blob/4.1.0/components/migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/migrator/v400/V400DBDataMigrator.java#L252) it doesn't set the status properly. Suggested solution is to modify [this](https://github.com/wso2-extensions/apim-migration-resources/blob/4.1.0/components/migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/migrator/v400/V400DBDataMigrator.java#L252) as following.

Change

```
...
    apiInfoDTO.setStatus(((GenericArtifactImpl) artifact).getLcState());
...
```
to

```
...
    apiInfoDTO.setStatus(artifact.getAttribute(APIConstants.API_OVERVIEW_STATUS));
...
```

**Affected Product Version:**
This was tested using APIM 2.6.0.103 and APIM 4.1.0.31.

**Steps to reproduce:**
1. Run APIM 2.6.0 pointed to MySQL database on localhost.
2. Populate data using [APIM Data Populator](https://github.com/wso2-extensions/apim-migration-resources/tree/master/apim-data-populator).
3. Stop APIM 2.6.0.
4. Follow steps on [Upgrading API Manager from 2.6.0 to 4.1.0](https://apim.docs.wso2.com/en/latest/install-and-setup/upgrading-wso2-api-manager/260-to-410/upgrading-from-260-to-410).
5. After running step 4.4, you will get this error.

**Comment by binodmx** [comment]
Here is the full error log.

```
ERROR - Framework FrameworkEvent ERROR

java.lang.NullPointerException: null

    at org.wso2.carbon.apimgt.migration.dao.APIMgtDAO.updateUUIDAndStatus(APIMgtDAO.java:756) ~[org.wso2.carbon.apimgt.migrate.client-4.1.0.36.jar:?]

    at org.wso2.carbon.apimgt.migration.migrator.v400.V400DBDataMigrator.moveUUIDToDBFromRegistry(V400DBDataMigrator.java:260) ~[org.wso2.carbon.apimgt.migrate.client-4.1.0.36.jar:?]

    at org.wso2.carbon.apimgt.migration.migrator.v400.V400DBDataMigrator.migrate(V400DBDataMigrator.java:95) ~[org.wso2.carbon.apimgt.migrate.client-4.1.0.36.jar:?]

    at org.wso2.carbon.apimgt.migration.migrator.client.V400Migration.migrate(V400Migration.java:58) ~[org.wso2.carbon.apimgt.migrate.client-4.1.0.36.jar:?]

    at org.wso2.carbon.apimgt.migration.APIMMigrationClient.executeMigration(APIMMigrationClient.java:87) ~[org.wso2.carbon.apimgt.migrate.client-4.1.0.36.jar:?]

    at org.wso2.carbon.apimgt.migration.APIMMigrationClient.completedServerStartup(APIMMigrationClient.java:64) ~[org.wso2.carbon.apimgt.migrate.client-4.1.0.36.jar:?]

    at org.wso2.carbon.core.internal.CarbonCoreServiceComponent.notifyAfter(CarbonCoreServiceComponent.java:264) ~[?:?]

    at org.wso2.carbon.core.internal.StartupFinalizerServiceComponent.completeInitialization(StartupFinalizerServiceComponent.java:218) ~[?:?]

    at org.wso2.carbon.core.internal.StartupFinalizerServiceComponent.serviceChanged(StartupFinalizerServiceComponent.java:323) ~[?:?]

    at org.eclipse.osgi.internal.serviceregistry.FilteredServiceListener.serviceChanged(FilteredServiceListener.java:113) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]

    at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:985) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]

    at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]

    at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:151) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]

    at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEventPrivileged(ServiceRegistry.java:866) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]

    at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEvent(ServiceRegistry.java:804) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]

    at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.register(ServiceRegistrationImpl.java:130) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]

    at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.registerService(ServiceRegistry.java:228) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]

    at org.eclipse.osgi.internal.framework.BundleContextImpl.registerService(BundleContextImpl.java:525) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]

    at org.eclipse.osgi.internal.framework.BundleContextImpl.registerService(BundleContextImpl.java:544) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]

    at org.wso2.carbon.throttling.agent.internal.ThrottlingAgentServiceComponent.registerThrottlingAgent(ThrottlingAgentServiceComponent.java:118) ~[org.wso2.carbon.tenant.throttling.agent_4.9.10.jar:?]

    at org.wso2.carbon.throttling.agent.internal.ThrottlingAgentServiceComponent.activate(ThrottlingAgentServiceComponent.java:96) ~[org.wso2.carbon.tenant.throttling.agent_4.9.10.jar:?]

    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_333]

    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_333]

    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_333]

    at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_333]

    at org.eclipse.equinox.internal.ds.model.ServiceComponent.activate(ServiceComponent.java:260) ~[org.eclipse.equinox.ds_1.4.400.v20160226-2036.jar:?]

    at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.activate(ServiceComponentProp.java:146) ~[org.eclipse.equinox.ds_1.4.400.v20160226-2036.jar:?]

    at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.build(ServiceComponentProp.java:345) ~[org.eclipse.equinox.ds_1.4.400.v20160226-2036.jar:?]

    at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponent(InstanceProcess.java:620) ~[org.eclipse.equinox.ds_1.4.400.v20160226-2036.jar:?]

    at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponents(InstanceProcess.java:197) ~[org.eclipse.equinox.ds_1.4.400.v20160226-2036.jar:?]

    at org.eclipse.equinox.internal.ds.Resolver.getEligible(Resolver.java:343) ~[org.eclipse.equinox.ds_1.4.400.v20160226-2036.jar:?]

    at org.eclipse.equinox.internal.ds.SCRManager.serviceChanged(SCRManager.java:222) ~[org.eclipse.equinox.ds_1.4.400.v20160226-2036.jar:?]

    at org.eclipse.osgi.internal.serviceregistry.FilteredServiceListener.serviceChanged(FilteredServiceListener.java:113) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]

    at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:985) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]

    at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]

    at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:151) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]

    at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEventPrivileged(ServiceRegistry.java:866) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]

    at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEvent(ServiceRegistry.java:804) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]

    at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.register(ServiceRegistrationImpl.java:130) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]

    at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.registerService(ServiceRegistry.java:228) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]

    at org.eclipse.osgi.internal.framework.BundleContextImpl.registerService(BundleContextImpl.java:525) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]

    at org.eclipse.osgi.internal.framework.BundleContextImpl.registerService(BundleContextImpl.java:544) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]

    at org.wso2.carbon.core.init.CarbonServerManager.initializeCarbon(CarbonServerManager.java:529) ~[org.wso2.carbon.core_4.6.3.1.jar:?]

    at org.wso2.carbon.core.init.CarbonServerManager.removePendingItem(CarbonServerManager.java:305) ~[org.wso2.carbon.core_4.6.3.1.jar:?]

    at org.wso2.carbon.core.init.PreAxis2ConfigItemListener.bundleChanged(PreAxis2ConfigItemListener.java:118) ~[org.wso2.carbon.core_4.6.3.1.jar:?]

    at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:973) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]

    at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]

    at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:345) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]

```

**Comment by Lakith-Rambukkanage** [comment]
The error is reproduced only when the db scripts in [Step 1](https://apim.docs.wso2.com/en/latest/install-and-setup/upgrading-wso2-api-manager/260-to-410/upgrading-from-260-to-410/#step-1-migrate-the-api-manager-configurations), Item `5. Disable versioning in the registry configuration` are not executed while migration. 

Following these two paths does not reproduce the error :
- If the older version was used with registry versioning enabled it is mandatory to run the script.
- If the older version was used with registry versioning disabled, the script is not needed to be run.


The documentation will be updated as enabling registry versioning is discouraged in newer versions and to avoid confusion.
