### ISSUE TITLE
After migrating APIM 2.2.0 to 3.1.0 unable to navigate to Lifecycle tab of an API In Publisher

### ISSUE THREAD

**Issue by TheRasanjana** [wso2-extensions/apim-migration-resources#7]
**Description:**
After migrating APIM 2.2.0 to 3.1.0 unable to navigate to Lifecycle tab of an API In Publisher Observed only with Oracle Databases setup.

#### Steps to reproduce:

1. Configure APIM 2.2.0 with **Oracle as database** for AM_DB, REG_DB and UM_DB.
2. Populate data by creating Tenants, APIs and Applications
3. Proceed the Migration by following 2.2.0 to 3.1.0 Migration doc. (IS migration client version : wso2is-migration-1.0.96)
4. Navigate to publisher and login with super tenant credentials.
5. Click on an API and Click on LifeCycle tab.

#### Actual output :

- LifeCycle tab is not getting loaded.
- Following error message is observed in the log.

2020-05-18 04:15:21,291] ERROR - UserAwareAPIProvider Failed to get API. API artifact corresponding to artifactId b3dd4422-e7d0-46f1-91f8-cd8521a4f766 does not exist
[2020-05-18 04:15:21,301] ERROR - ApisApiServiceImpl Requested API with Id 'b3dd4422-e7d0-46f1-91f8-cd8521a4f766' not found
org.wso2.carbon.apimgt.api.APIMgtResourceNotFoundException: Failed to get API. API artifact corresponding to artifactId b3dd4422-e7d0-46f1-91f8-cd8521a4f766 does not exist
	at org.wso2.carbon.apimgt.impl.AbstractAPIManager.getAPIbyUUID_aroundBody20(AbstractAPIManager.java:523) ~[org.wso2.carbon.apimgt.impl_6.6.163.jar:?]
	at org.wso2.carbon.apimgt.impl.AbstractAPIManager.getAPIbyUUID(AbstractAPIManager.java:489) ~[org.wso2.carbon.apimgt.impl_6.6.163.jar:?]
[org.wso2.carbon.identity.context.rewrite.valve_1.4.0.jar:?]
	at org.wso2.carbon.identity.authz.valve.AuthorizationValve.invoke(AuthorizationValve.java:110) [org.wso2.carbon.identity.authz.valve_1.4.0.jar:?]
	at org.wso2.carbon.identity.auth.valve.AuthenticationValve.invoke(AuthenticationValve.java:75) [org.wso2.carbon.identity.auth.valve_1.4.0.jar:?]
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java:99) [org.wso2.carbon.tomcat.ext_4.6.0.jar:?]
	at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:49) [org.wso2.carbon.tomcat.ext_4.6.0.jar:?]
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:62) [org.wso2.carbon.tomcat.ext_4.6.0.jar:?]
	at org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve.invoke(CarbonStuckThreadDetectionValve.java:145) [org.wso2.carbon.tomcat.ext_4.6.0.jar:?]
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:688) [tomcat_9.0.31.wso2v1.jar:?]
	at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:57) [org.wso2.carbon.tomcat.ext_4.6.0.jar:?]
	at org.wso2.carbon.tomcat.ext.valves.RequestCorrelationIdValve.invoke(RequestCorrelationIdValve.java:119) [org.wso2.carbon.tomcat.ext_4.6.0.jar:?]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat_9.0.31.wso2v1.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_242]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_242]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat_9.0.31.wso2v1.jar:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
[2020-05-18 04:15:23,340] ERROR - UserAwareAPIProvider Error while retrieving the lifecycle actions for lifecycle: APILifeCycle in lifecycle state: null
org.wso2.carbon.governance.api.exception.GovernanceException: Error while retrieving the lifecycle actions for lifecycle: APILifeCycle in lifecycle state: null

**Comment by rmsamitha** [comment]
The root cause was that the registry versioning disabling scripts executed on reg db were not commited, within that DB connection session. So those DML changes were not reflected into the reg db. So it had caused missing a mapping entry in reg_resource_property table for the type property of the tenant's keystore jks file. After doing the migration with "committing" each oracle scripts, the issue can be fixed.  Added a note in the docs with https://github.com/wso2/docs-apim/pull/1291/files
